#!/usr/bin/env bash
#
# CHANGELOG Generator from Git History
# Bounty: claude-builders-bounty #1
# Usage: bash changelog.sh [output_file]
#

set -euo pipefail

OUTPUT_FILE="${1:-CHANGELOG.md}"

# --- Colors ---
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# --- Check git repo ---
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo -e "${RED}Error: Not in a git repository${NC}"
    exit 1
fi

# --- Get last tag ---
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

if [ -n "$LAST_TAG" ]; then
    echo -e "${GREEN}Generating CHANGELOG since tag: ${LAST_TAG}${NC}"
    RANGE="${LAST_TAG}..HEAD"
else
    echo -e "${YELLOW}No tags found, generating from all commits${NC}"
    RANGE="HEAD"
fi

# --- Fetch commits ---
COMMITS=$(git log "$RANGE" --pretty=format:"%H|%ad|%s" --date=short 2>/dev/null || echo "")

if [ -z "$COMMITS" ]; then
    echo -e "${RED}No commits found${NC}"
    exit 1
fi

TOTAL=$(echo "$COMMITS" | wc -l | tr -d ' ')
echo -e "${GREEN}Found ${TOTAL} commits${NC}"

# --- Categorize commits ---
ADDED=()
CHANGED=()
FIXED=()
REMOVED=()

while IFS='|' read -r HASH DATE MSG; do
    SHORT_HASH="${HASH:0:8}"
    MSG_LOWER=$(echo "$MSG" | tr '[:upper:]' '[:lower:]')

    # Check conventional commit prefix first
    if [[ "$MSG_LOWER" =~ ^feat(\(.+\))?: ]]; then
        ADDED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
    elif [[ "$MSG_LOWER" =~ ^fix(\(.+\))?: ]]; then
        FIXED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
    elif [[ "$MSG_LOWER" =~ ^chore(\(.+\))?: ]]; then
        CHANGED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
    elif [[ "$MSG_LOWER" =~ ^refactor(\(.+\))?: ]]; then
        CHANGED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
    elif [[ "$MSG_LOWER" =~ ^docs(\(.+\))?: ]]; then
        CHANGED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
    elif [[ "$MSG_LOWER" =~ ^test(\(.+\))?: ]]; then
        CHANGED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
    elif [[ "$MSG_LOWER" =~ ^style(\(.+\))?: ]]; then
        CHANGED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
    elif [[ "$MSG_LOWER" =~ ^perf(\(.+\))?: ]]; then
        CHANGED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
    elif [[ "$MSG_LOWER" =~ ^ci(\(.+\))?: ]]; then
        CHANGED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
    elif [[ "$MSG_LOWER" =~ ^build(\(.+\))?: ]]; then
        CHANGED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
    elif [[ "$MSG_LOWER" =~ ^revert(\(.+\))?: ]]; then
        REMOVED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
    else
        # Keyword matching fallback
        CATEGORIZED=false
        for KW in "add" "create" "new" "implement" "feature" "introduce"; do
            if [[ "$MSG_LOWER" == *"$KW"* ]]; then
                ADDED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
                CATEGORIZED=true
                break
            fi
        done
        if [ "$CATEGORIZED" = false ]; then
            for KW in "fix" "bug" "patch" "resolve" "correct" "repair"; do
                if [[ "$MSG_LOWER" == *"$KW"* ]]; then
                    FIXED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
                    CATEGORIZED=true
                    break
                fi
            done
        fi
        if [ "$CATEGORIZED" = false ]; then
            for KW in "remove" "delete" "drop" "deprecate" "clean"; do
                if [[ "$MSG_LOWER" == *"$KW"* ]]; then
                    REMOVED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
                    CATEGORIZED=true
                    break
                fi
            done
        fi
        if [ "$CATEGORIZED" = false ]; then
            CHANGED+=("- ${MSG} (${SHORT_HASH}) - ${DATE}")
        fi
    fi
done <<< "$COMMITS"

# --- Generate CHANGELOG ---
TODAY=$(date +%Y-%m-%d)

{
    echo "# Changelog"
    echo ""
    echo "All notable changes to this project will be documented in this file."
    echo ""
    echo "## [Unreleased] - ${TODAY}"
    echo ""

    if [ ${#ADDED[@]} -gt 0 ]; then
        echo "### Added"
        echo ""
        printf '%s\n' "${ADDED[@]}"
        echo ""
    fi

    if [ ${#CHANGED[@]} -gt 0 ]; then
        echo "### Changed"
        echo ""
        printf '%s\n' "${CHANGED[@]}"
        echo ""
    fi

    if [ ${#FIXED[@]} -gt 0 ]; then
        echo "### Fixed"
        echo ""
        printf '%s\n' "${FIXED[@]}"
        echo ""
    fi

    if [ ${#REMOVED[@]} -gt 0 ]; then
        echo "### Removed"
        echo ""
        printf '%s\n' "${REMOVED[@]}"
        echo ""
    fi

    echo "---"
    echo ""
    echo "_Generated by changelog.sh on ${TODAY}_"
} > "$OUTPUT_FILE"

echo -e "${GREEN}CHANGELOG.md generated successfully!${NC}"
echo -e "${GREEN}Output: ${OUTPUT_FILE}${NC}"
echo ""
echo "Summary:"
echo "  Added:   ${#ADDED[@]} commits"
echo "  Changed: ${#CHANGED[@]} commits"
echo "  Fixed:   ${#FIXED[@]} commits"
echo "  Removed: ${#REMOVED[@]} commits"
