"""
Review Formatter for PR Review Agent
"""

from typing import Dict, Any


def format_review_markdown(review_data: Dict[str, Any]) -> str:
    """
    Format structured review data as Markdown.
    
    Args:
        review_data: Dictionary with review data
        
    Returns:
        Formatted Markdown string
    """
    markdown = []
    
    # Summary
    markdown.append("## 📝 Summary")
    markdown.append("")
    markdown.append(review_data.get("summary", "No summary provided"))
    markdown.append("")
    
    # Risks
    risks = review_data.get("risks", [])
    if risks:
        markdown.append("## ⚠️ Identified Risks")
        markdown.append("")
        for risk in risks:
            markdown.append(f"- {risk}")
        markdown.append("")
    
    # Suggestions
    suggestions = review_data.get("suggestions", [])
    if suggestions:
        markdown.append("## 💡 Improvement Suggestions")
        markdown.append("")
        for suggestion in suggestions:
            markdown.append(f"- {suggestion}")
        markdown.append("")
    
    # Confidence
    confidence = review_data.get("confidence", "Unknown")
    markdown.append(f"## 🔍 Confidence Score: **{confidence}**")
    markdown.append("")
    
    # Footer
    markdown.append("---")
    markdown.append("*Generated by Claude Code PR Review Agent*")
    
    return "\n".join(markdown)