#!/usr/bin/env python3
"""
claude-review — PR Review Agent for Claude Code
Analyzes PR diffs and produces structured Markdown reviews.

Usage:
    claude-review --pr https://github.com/owner/repo/pull/123
    claude-review --diff path/to/diff.patch
"""

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from typing import Optional

# Patterns for risk detection
RISK_PATTERNS = [
    (re.compile(r'remove|delete|drop', re.I), "Destructive operation detected", "HIGH"),
    (re.compile(r'password|secret|token|key', re.I), "Potential credential handling", "HIGH"),
    (re.compile(r'eval\(|exec\(', re.I), "Code injection risk", "CRITICAL"),
    (re.compile(r'SQL|query|execute', re.I), "SQL operation — check for injection", "MEDIUM"),
    (re.compile(r'os\.system|subprocess', re.I), "Shell command execution", "HIGH"),
    (re.compile(r'TODO|FIXME|HACK|XXX', re.I), "Unresolved technical debt", "LOW"),
    (re.compile(r'console\.log|print\(', re.I), "Debug output in production code", "LOW"),
    (re.compile(r'any\b', re.I), "Loose typing — consider specific types", "LOW"),
]

# Improvement patterns
IMPROVEMENT_PATTERNS = [
    (re.compile(r'for.*range.*len\('), "Consider using enumerate() for cleaner iteration"),
    (re.compile(r'if.*!=.*None'), "Use 'if x is not None' (PEP 8)"),
    (re.compile(r'except:'), "Avoid bare except — specify exception type"),
    (re.compile(r'import \*'), "Avoid wildcard imports — be explicit"),
]


@dataclass
class ReviewResult:
    summary: str
    risks: list[tuple[str, str]]
    improvements: list[str]
    confidence: str
    stats: dict

    def to_markdown(self) -> str:
        lines = [
            "## 🤖 Claude Code PR Review",
            "",
            f"**Confidence:** {self.confidence}",
            "",
            "### 📋 Summary",
            f"{self.summary}",
            "",
        ]

        if self.risks:
            lines.append("### ⚠️ Identified Risks")
            lines.append("")
            for risk, severity in self.risks:
                emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"}.get(severity, "⚪")
                lines.append(f"- {emoji} **[{severity}]** {risk}")
            lines.append("")

        if self.improvements:
            lines.append("### 💡 Improvement Suggestions")
            lines.append("")
            for imp in self.improvements:
                lines.append(f"- {imp}")
            lines.append("")

        lines.extend([
            "### 📊 Stats",
            f"- Files changed: {self.stats.get('files', 0)}",
            f"- Additions: {self.stats.get('additions', 0)}",
            f"- Deletions: {self.stats.get('deletions', 0)}",
            "",
            "---",
            "*Generated by claude-review agent*",
        ])

        return "\n".join(lines)


def fetch_pr_diff(pr_url: str) -> str:
    """Fetch PR diff using gh CLI."""
    # Extract owner/repo/pr_number from URL
    match = re.search(r'github\.com/([^/]+/[^/]+)/pull/(\d+)', pr_url)
    if not match:
        raise ValueError(f"Invalid PR URL: {pr_url}")

    owner_repo, pr_number = match.groups()

    result = subprocess.run(
        ["gh", "pr", "diff", pr_number, "--repo", owner_repo],
        capture_output=True, text=True, timeout=30
    )

    if result.returncode != 0:
        raise RuntimeError(f"Failed to fetch PR diff: {result.stderr}")

    return result.stdout


def fetch_diff_from_file(path: str) -> str:
    """Read diff from local file."""
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def analyze_diff(diff: str) -> ReviewResult:
    """Analyze a diff and produce a structured review."""
    lines = diff.split("\n")

    # Stats
    files = set()
    additions = 0
    deletions = 0

    for line in lines:
        if line.startswith("+++ b/"):
            files.add(line[6:])
        elif line.startswith("+") and not line.startswith("+++"):
            additions += 1
        elif line.startswith("-") and not line.startswith("---"):
            deletions += 1

    # Risk analysis
    risks = []
    improvements = []
    seen_risks = set()

    for line in lines:
        if line.startswith("+"):
            content = line[1:]
            # Check risks
            for pattern, desc, severity in RISK_PATTERNS:
                if pattern.search(content) and desc not in seen_risks:
                    risks.append((desc, severity))
                    seen_risks.add(desc)
            # Check improvements
            for pattern, suggestion in IMPROVEMENT_PATTERNS:
                if pattern.search(content) and suggestion not in improvements:
                    improvements.append(suggestion)

    # Generate summary
    file_count = len(files)
    if additions > deletions:
        direction = f"adds {additions} lines across {file_count} files"
    elif deletions > additions:
        direction = f"removes {deletions} lines across {file_count} files"
    else:
        direction = f"modifies {file_count} files with balanced changes"

    summary = f"This PR {direction}."

    # Determine confidence
    total_changes = additions + deletions
    if total_changes < 50:
        confidence = "High"
    elif total_changes < 200:
        confidence = "Medium"
    else:
        confidence = "Low"

    # If no risks found, add a positive note
    if not risks:
        improvements.insert(0, "No significant risks detected — looks clean!")

    return ReviewResult(
        summary=summary,
        risks=risks,
        improvements=improvements,
        confidence=confidence,
        stats={"files": file_count, "additions": additions, "deletions": deletions},
    )


def post_review_to_pr(pr_url: str, review: ReviewResult):
    """Post the review as a PR comment using gh CLI."""
    match = re.search(r'github\.com/([^/]+/[^/]+)/pull/(\d+)', pr_url)
    if not match:
        return

    owner_repo, pr_number = match.groups()
    markdown = review.to_markdown()

    result = subprocess.run(
        ["gh", "pr", "comment", pr_number, "--repo", owner_repo, "--body", markdown],
        capture_output=True, text=True, timeout=30
    )

    if result.returncode != 0:
        print(f"Warning: Failed to post comment: {result.stderr}", file=sys.stderr)
    else:
        print("✅ Review posted to PR!")


def main():
    parser = argparse.ArgumentParser(description="Claude Code PR Review Agent")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--pr", help="GitHub PR URL to review")
    group.add_argument("--diff", help="Path to diff/patch file")
    parser.add_argument("--output", help="Save review to file instead of posting")
    parser.add_argument("--json", action="store_true", help="Output as JSON")

    args = parser.parse_args()

    # Get diff
    if args.pr:
        print(f"Fetching PR diff: {args.pr}")
        diff = fetch_pr_diff(args.pr)
    else:
        diff = fetch_diff_from_file(args.diff)

    if not diff.strip():
        print("Error: Empty diff", file=sys.stderr)
        sys.exit(1)

    # Analyze
    print("Analyzing changes...")
    review = analyze_diff(diff)

    # Output
    if args.json:
        print(json.dumps({
            "summary": review.summary,
            "risks": review.risks,
            "improvements": review.improvements,
            "confidence": review.confidence,
            "stats": review.stats,
        }, indent=2))
    elif args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(review.to_markdown())
        print(f"✅ Review saved to {args.output}")
    elif args.pr:
        print(review.to_markdown())
        post_review_to_pr(args.pr, review)
    else:
        print(review.to_markdown())


if __name__ == "__main__":
    main()
